/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.google.ads.googleads.v0.enums.CustomPlaceholderFieldEnum', null, global);
goog.exportSymbol('proto.google.ads.googleads.v0.enums.CustomPlaceholderFieldEnum.CustomPlaceholderField', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.ads.googleads.v0.enums.CustomPlaceholderFieldEnum = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.ads.googleads.v0.enums.CustomPlaceholderFieldEnum, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.google.ads.googleads.v0.enums.CustomPlaceholderFieldEnum.displayName = 'proto.google.ads.googleads.v0.enums.CustomPlaceholderFieldEnum';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.ads.googleads.v0.enums.CustomPlaceholderFieldEnum.prototype.toObject = function(opt_includeInstance) {
  return proto.google.ads.googleads.v0.enums.CustomPlaceholderFieldEnum.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.ads.googleads.v0.enums.CustomPlaceholderFieldEnum} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.ads.googleads.v0.enums.CustomPlaceholderFieldEnum.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.ads.googleads.v0.enums.CustomPlaceholderFieldEnum}
 */
proto.google.ads.googleads.v0.enums.CustomPlaceholderFieldEnum.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.ads.googleads.v0.enums.CustomPlaceholderFieldEnum;
  return proto.google.ads.googleads.v0.enums.CustomPlaceholderFieldEnum.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.ads.googleads.v0.enums.CustomPlaceholderFieldEnum} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.ads.googleads.v0.enums.CustomPlaceholderFieldEnum}
 */
proto.google.ads.googleads.v0.enums.CustomPlaceholderFieldEnum.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.ads.googleads.v0.enums.CustomPlaceholderFieldEnum.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.ads.googleads.v0.enums.CustomPlaceholderFieldEnum.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.ads.googleads.v0.enums.CustomPlaceholderFieldEnum} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.ads.googleads.v0.enums.CustomPlaceholderFieldEnum.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};


/**
 * @enum {number}
 */
proto.google.ads.googleads.v0.enums.CustomPlaceholderFieldEnum.CustomPlaceholderField = {
  UNSPECIFIED: 0,
  UNKNOWN: 1,
  ID: 2,
  ID2: 3,
  ITEM_TITLE: 4,
  ITEM_SUBTITLE: 5,
  ITEM_DESCRIPTION: 6,
  ITEM_ADDRESS: 7,
  PRICE: 8,
  FORMATTED_PRICE: 9,
  SALE_PRICE: 10,
  FORMATTED_SALE_PRICE: 11,
  IMAGE_URL: 12,
  ITEM_CATEGORY: 13,
  FINAL_URLS: 14,
  FINAL_MOBILE_URLS: 15,
  TRACKING_URL: 16,
  CONTEXTUAL_KEYWORDS: 17,
  ANDROID_APP_LINK: 18,
  SIMILAR_IDS: 19,
  IOS_APP_LINK: 20,
  IOS_APP_STORE_ID: 21
};

goog.object.extend(exports, proto.google.ads.googleads.v0.enums);
